name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # گرفتن کد پروژه
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب Java (مهم برای Gradle)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # نصب Flutter (نسخه پایدار و بدون خطا)
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # بررسی نسخه‌ها
      - name: Flutter Doctor
        run: flutter doctor

      # گرفتن پکیج‌ها
      - name: Install dependencies
        run: flutter pub get

      # اجرای تست‌ها (اختیاری ولی خوبه)
      - name: Run tests
        run: flutter test
        continue-on-error: true

      # ساخت APK Release
      - name: Build APK
        run: flutter build apk --release

      # ذخیره خروجی APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
